### ISSUE TITLE
Pretrained models missing 

### ISSUE THREAD

**Issue by fb1812** [leila68/safety_evaluation_with_llm#1]
Hi, it seems like the models are missing and I am not able to run the demo. 
Would be possible to add them? 
Thank you!

**Comment by leila68** [comment]
Hi,
You can download it from this link:
https://github.com/OlafenwaMoses/ImageAI/releases/download/3.0.0-pretrained/retinanet_resnet50_fpn_coco-eeacb38b.pth/
<https://imageai.readthedocs.io/en/latest/detection/>
It should work.

**Comment by fb1812** [comment]
thank you! And where should I find the video? On KITTI I am seeing only images or annotations . 

Thank you!

**Comment by leila68** [comment]
No problem. You can try any video, but use a very short one because it
takes time. On KITTI, you can turn image frames into a video. I think there
is a script for that on my GitHub too.

**Comment by fb1812** [comment]
Fantastic, it worked! Do you also have a paper or reference to cite your work? :)
